exports.directoriesToCreate = [
  'models',
  'controllers',
  'helpers',
  'utils',
  'config',
  'routes',
  'test',
  'uploads',
  'middlewares',
]

exports.topLevelFilesToCreate = [
  'app.js',
  '.env',
  '.prettierrc',
  '.eslintrc.json',
  '.gitignore',
  'swagger.json',
  'README.md',
  'server.js',
  'Procfile',
  'requests.rest',
]

exports.dependenciesToInstall = [
  'bcryptjs',
  'compression',
  'cors',
  'dotenv',
  'esm',
  'express',
  'express-mongo-sanitize',
  'express-rate-limit',
  'helmet',
  'hpp',
  'html-to-text',
  'jsonwebtoken',
  'mongoose',
  'morgan',
  'multer',
  'nodemailer',
  'sharp',
  'slugify',
  'validator',
  'xss-clean',
  'cloudinary',
  'global',
  'jest',
  'swagger-ui-express',
  'node-fetch',
]

exports.devDependenciesToInstall = [
  'eslint',
  'eslint-config-airbnb',
  'eslint-config-prettier',
  'eslint-plugin-import',
  'eslint-plugin-jsx-a11y',
  'eslint-plugin-node',
  'eslint-plugin-prettier',
  'eslint-plugin-react prettier',
]
